# -*- mode: ruby -*-
# vi: set ft=ruby :

# The private network IP of the VM. You will use this IP to connect to OpenShift.
PUBLIC_ADDRESS="10.1.2.3"

# Number of virtualized CPUs
VM_CPU = ENV['VM_CPU'] || 2

# Amount of available RAM
VM_MEMORY = ENV['VM_MEMORY'] || 4096

# Validate required plugins
REQUIRED_PLUGINS = %w(vagrant-service-manager vagrant-registration)
errors = []

def message(name)
  "#{name} plugin is not installed, run `vagrant plugin install #{name}` to install it."
end
# Validate and collect error message if plugin is not installed
REQUIRED_PLUGINS.each { |plugin| errors << message(plugin) unless Vagrant.has_plugin?(plugin) }
unless errors.empty?
  msg = errors.size > 1 ? "Errors: \n* #{errors.join("\n* ")}" : "Error: #{errors.first}"
  fail Vagrant::Errors::VagrantError.new, msg
end

Vagrant.configure(2) do |config|
  config.vm.box = "cdkv2"

  # DWM: sshfs
  #config.vm.synced_folder "/guests/sharedfolder", "/sharedfolder", type: "sshfs"
  #config.vm.synced_folder "/home/redhat/ticketmonster/", "/sharedfolder/ticketmonster/", type: "rsync"

  config.vm.provider "virtualbox" do |v, override|
    v.memory = VM_MEMORY
    v.cpus   = VM_CPU
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.provider "libvirt" do |v, override|
    v.memory = VM_MEMORY
    v.cpus   = VM_CPU
    v.driver = "kvm"
  end

  config.vm.network "private_network", ip: "#{PUBLIC_ADDRESS}"

  if ENV.has_key?('SUB_USERNAME') && ENV.has_key?('SUB_PASSWORD')
    config.registration.username = ENV['SUB_USERNAME']
    config.registration.password = ENV['SUB_PASSWORD']
  end

  config.servicemanager.services = "docker"

  config.vm.provision "shell", "privileged": false, inline: <<-SHELL
    cd /home/vagrant/
    git clone https://github.com/eivantsov/ticketmonster.git
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    systemctl disable docker 2>&1
    systemctl stop docker 2>&1
    subscription-manager repos --enable=rhel-server-rhscl-7-rpms
    subscription-manager repos --enable=rhel-7-server-extras-rpms
    yum install -y maven30 java-1.8.0-openjdk-devel
    yum update -y docker 
    echo 'OPTIONS="--selinux-enabled -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock"' >> /etc/sysconfig/docker
    systemctl start docker
    sed -i 's/SELINUX=enforcing/SELINUX=permissive/' /etc/selinux/config
    setenforce 0
    docker run -i --rm --entrypoint /bin/cat registry.access.redhat.com/openshift3/ose:v3.1.1.6 /usr/bin/oc > /usr/bin/oc
    chmod +x /usr/bin/oc
    curl https://dl.dropboxusercontent.com/u/119656/henge > /usr/bin/henge
    chmod +x /usr/bin/henge
    docker pull dustymabe/ansible-container
    docker tag dustymabe/ansible-container ansible-container-builder
    docker pull dustymabe/mysql
    docker pull karm/mod_cluster-master-dockerhub
    docker pull rafabene/wildfly-admin
  SHELL
end
